/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStartedSidebar: [
    'getting-started/intro',
    {
      type: 'category',
      label: '🚀 Fundamentals',
      collapsed: false,
      items: ['getting-started/architecture', 'getting-started/quickstart'],
    },
    {
      type: 'category',
      label: '🛠️ Modding Guides',
      items: [
        'development/modding-guides/csharp-modding',
        'development/modding-guides/lua-modding',
        'development/modding-guides/rust-modding',
        'development/modding-guides/typescript-modding',
        'development/modding-guides/prepare-content-workshop',
        'development/modding-guides/prepare-content-gregmodstore',
      ],
    },
  ],
  bridgesSidebar: [
    'development/api-reference/game-system-bridges',
    {
      type: 'category',
      label: '🌉 Engine Services',
      collapsed: false,
      items: [
        'content-creation/content-creation-introduction',
        'content-creation/content-creation-custom-servers',
        'content-creation/content-creation-custom-switches',
        'content-creation/content-creation-custom-customers',
        'content-creation/content-creation-custom-network-items',
        'content-creation/content-creation-custom-employees',
        'content-creation/content-creation-custom-furniture',
        'content-creation/content-creation-model-overrides',
      ],
    },
  ],
  apiSidebar: [
    'development/api-reference/greg-hooks-catalog',
    {
      type: 'category',
      label: '⚓ Hooks Library',
      items: [{type: 'autogenerated', dirName: '02_development/hooks-library'}],
    },
  ],
  tutorialsSidebar: [
    {
      type: 'category',
      label: '🎓 Tutorials',
      collapsed: false,
      items: [
        'development/tutorials/hexviewer-csharp',
        'development/tutorials/hexviewer-lua',
        'development/tutorials/hexviewer-rust',
        'development/tutorials/hexviewer-ts',
      ],
    },
    'design-system/visual-philosophy',
  ],
  roadmapSidebar: [
    {
      type: 'category',
      label: '🗺️ Roadmap',
      collapsed: false,
      items: [
        'development/roadmap/overview',
        'development/roadmap/phase-5-economy',
        'development/roadmap/phase-6-hardware',
        'development/roadmap/phase-8-unity-api',
        'development/roadmap/phase-9-community-platform',
        'development/roadmap/phase-10-infra-performance',
        'development/roadmap/phase-11-audio-and-immersive',
      ],
    },
  ],
  communitySidebar: [
    {
      type: 'category',
      label: '🧩 Community Hub (WIP)',
      collapsed: false,
      items: [
        'community/mod-index',
        'community/community-readiness-index',
        'community/precheck-readiness-matrix',
        'community/community-mods-compatibility',
        'community/mod-security-policy',
        'community/migration-guide',
        'community/mod-conflict-resolution',
        'community/conflict-resolution',
        'community/eol-system-guide',
      ],
    },
    {
      type: 'category',
      label: '🛠️ Community Building (WIP)',
      items: [
        'community/custom-content-guide',
        'community/network-infrastructure-guide',
        'community/server-builder-guide',
        'community/warehouse-logistics-guide',
        'community/power-management-guide',
        'community/advanced-gameplay-modes',
        'community/floor-layout-guide',
        'community/performance-guide',
        'community/performance-optimization-guide',
        'community/accessibility-guide',
        'community/technician-management-guide',
        'community/asset-management-guide',
        'community/sound-environment-guide',
      ],
    },
    {
      type: 'category',
      label: '📣 Governance & Collaboration (WIP)',
      items: [
        'community/changelog-notes',
        'community/community-feature-requests',
        'community/framework-addons',
        'community/docusaurus-workflow',
      ],
    },
    'legal/sponsors',
  ],
};

module.exports = sidebars;
