/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  gettingStartedSidebar: [
    'getting-started/intro',
    {
      type: 'category',
      label: '🚀 Fundamentals',
      collapsed: false,
      items: ['getting-started/architecture', 'getting-started/quickstart'],
    },
    {
      type: 'category',
      label: '🛠️ Modding Guides',
      items: [
        '02_development/modding-guides/csharp-modding',
        '02_development/modding-guides/lua-modding',
        '02_development/modding-guides/rust-modding',
        '02_development/modding-guides/typescript-modding',
      ],
    },
  ],
  bridgesSidebar: [
    '02_development/api-reference/game-system-bridges',
    {
      type: 'category',
      label: '🌉 Engine Services',
      collapsed: false,
      items: [
        'content-creation/content-creation-introduction',
        'content-creation/content-creation-custom-servers',
        'content-creation/content-creation-custom-switches',
        'content-creation/content-creation-custom-customers',
        'content-creation/content-creation-custom-network-items',
        'content-creation/content-creation-custom-employees',
        'content-creation/content-creation-custom-furniture',
        'content-creation/content-creation-model-overrides',
      ],
    },
  ],
  apiSidebar: [
    '02_development/concepts/hooks-and-events',
    '02_development/api-reference/greg-hooks-catalog',
    {
      type: 'category',
      label: '⚓ Hooks Library',
      items: [{type: 'autogenerated', dirName: '02_development/hooks-library'}],
    },
  ],
  tutorialsSidebar: [
    {
      type: 'category',
      label: '🎓 Tutorials',
      collapsed: false,
      items: [
        '02_development/tutorials/hexviewer-csharp',
        '02_development/tutorials/hexviewer-lua',
        '02_development/tutorials/hexviewer-rust',
        '02_development/tutorials/hexviewer-ts',
      ],
    },
    'design-system/visual-philosophy',
  ],
  communitySidebar: [
    'community/mod-index',
    'community/framework-addons',
    'community/docusaurus-workflow',
    'legal/sponsors',
  ],
};

module.exports = sidebars;
