/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  wikiSidebar: [
    {
      type: 'category',
      label: '🚀 Start',
      collapsed: false,
      items: ['getting-started/intro', 'getting-started/quickstart', 'getting-started/architecture'],
    },
    {
      type: 'category',
      label: '📡 API',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Concepts',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: '02_development/concepts'}],
        },
        {
          type: 'category',
          label: 'Reference',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: '02_development/api-reference'}],
        },
        {
          type: 'category',
          label: 'Hooks Library',
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'greg.CONTENT.*',
              collapsed: true,
              items: [{type: 'autogenerated', dirName: '02_development/hooks-library/content'}],
            },
            {
              type: 'category',
              label: 'greg.CUSTOMER.*',
              collapsed: true,
              items: [{type: 'autogenerated', dirName: '02_development/hooks-library/customer'}],
            },
            {
              type: 'category',
              label: 'greg.EMPLOYEE.*',
              collapsed: true,
              items: [{type: 'autogenerated', dirName: '02_development/hooks-library/employee'}],
            },
            {
              type: 'category',
              label: 'greg.GAMEPLAY.*',
              collapsed: true,
              items: [{type: 'autogenerated', dirName: '02_development/hooks-library/gameplay'}],
            },
            {
              type: 'category',
              label: 'greg.INPUT.*',
              collapsed: true,
              items: [{type: 'autogenerated', dirName: '02_development/hooks-library/input'}],
            },
            {
              type: 'category',
              label: 'greg.NETWORK.*',
              collapsed: true,
              items: [{type: 'autogenerated', dirName: '02_development/hooks-library/network'}],
            },
            {
              type: 'category',
              label: 'greg.PLAYER.*',
              collapsed: true,
              items: [{type: 'autogenerated', dirName: '02_development/hooks-library/player'}],
            },
            {
              type: 'category',
              label: 'greg.RACK.*',
              collapsed: true,
              items: [{type: 'autogenerated', dirName: '02_development/hooks-library/rack'}],
            },
            {
              type: 'category',
              label: 'greg.SERVER.*',
              collapsed: true,
              items: [{type: 'autogenerated', dirName: '02_development/hooks-library/server'}],
            },
            {
              type: 'category',
              label: 'greg.SYSTEM.*',
              collapsed: true,
              items: [{type: 'autogenerated', dirName: '02_development/hooks-library/system'}],
            },
            {
              type: 'category',
              label: 'greg.UI.*',
              collapsed: true,
              items: [{type: 'autogenerated', dirName: '02_development/hooks-library/ui'}],
            },
            {
              type: 'category',
              label: 'greg.WORLD.*',
              collapsed: true,
              items: [{type: 'autogenerated', dirName: '02_development/hooks-library/world'}],
            },
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🎓 Guides',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Languages',
          collapsed: true,
          items: [
            'development/modding-guides/csharp-modding',
            'development/modding-guides/lua-modding',
            'development/modding-guides/rust-modding',
            'development/modding-guides/typescript-modding',
          ],
        },
        {
          type: 'category',
          label: 'HexViewer',
          collapsed: true,
          items: [
            'development/tutorials/hexviewer-csharp',
            'development/tutorials/hexviewer-lua',
            'development/tutorials/hexviewer-rust',
            'development/tutorials/hexviewer-ts',
          ],
        },
        {
          type: 'category',
          label: 'Content Creation',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'content-creation'}],
        },
        {
          type: 'category',
          label: 'Publishing',
          collapsed: true,
          items: [
            'development/modding-guides/prepare-content-gregmodstore',
            'development/modding-guides/prepare-content-workshop',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: '🖥️ UI',
      collapsed: true,
      items: [
        'design-system/visual-philosophy',
        'development/ui/architecture',
        'development/ui/custom-ugui-csharp',
        'development/ui/replacing-vanilla-ui',
      ],
    },
    {
      type: 'category',
      label: '⚙️ Advanced',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Multiplayer',
          collapsed: true,
          items: [
            'community/multiplayer-architecture',
            'community/multiplayer-readiness',
            'community/multiplayer-dev-guide',
            'community/multiplayer-troubleshooting',
            'community/relay-protocol',
          ],
        },
        {
          type: 'category',
          label: 'Performance',
          collapsed: true,
          items: ['community/performance-guide', 'community/performance-optimization-guide'],
        },
        {
          type: 'category',
          label: 'Network',
          collapsed: true,
          items: ['community/network-infrastructure-guide', 'community/network-advanced-guide'],
        },
        {
          type: 'category',
          label: 'Security',
          collapsed: true,
          items: ['community/mod-security-policy', 'community/mod-conflict-resolution'],
        },
      ],
    },
    {
      type: 'category',
      label: '🏢 Operations',
      collapsed: true,
      items: [
        'community/server-builder-guide',
        'community/floor-layout-guide',
        'community/power-management-guide',
      ],
    },
    {
      type: 'category',
      label: '🧰 Tools',
      collapsed: true,
      items: [
        'tools/overview',
        'tools/core-runtime-tooling',
        'tools/reverse-debug-tooling',
        'tools/publishing-platform-tooling',
        'tools/workshop-uploader',
      ],
    },
    {
      type: 'category',
      label: '🤝 Community',
      collapsed: true,
      items: [{type: 'autogenerated', dirName: '04_community'}],
    },
    {
      type: 'category',
      label: '🗺️ Roadmap',
      collapsed: true,
      items: [
        'development/roadmap/overview',
        'development/roadmap/phase-5-economy',
        'development/roadmap/phase-6-hardware',
        'development/roadmap/phase-8-unity-api',
        'development/roadmap/phase-9-community-platform',
        'development/roadmap/phase-10-infra-performance',
        'development/roadmap/phase-11-audio-and-immersive',
        'development/roadmap/phase-12-liveops-and-systems',
      ],
    },
    {
      type: 'category',
      label: '⚖️ Legal',
      collapsed: true,
      items: ['legal/sponsors'],
    },
  ],
};

module.exports = sidebars;
